// apps/react-host/src/app/i-frame/i-frame.tsx
import styles from './i-frame.module.css';

/* eslint-disable-next-line */
export interface IFrameProps {}

export function IFrame(props: IFrameProps) {
  return (
    <div className={styles['container']}>
      <iframe title="iframe example" src="http://localhost:4202/react-module/mui" width="1000" height="600"></iframe>
    </div>
  );
}

export default IFrame;

// apps/angular-host/src/app/iframe/iframe.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'module-federation-web-components-iframe',
  templateUrl: './iframe.component.html',
  styleUrls: ['./iframe.component.css'],
})
export class IframeComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<iframe title="iframe example" src="http://localhost:4200/angular-module/material" width="1000" height="600"></iframe>
