// apps/angular-host/src/app/app.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'module-federation-web-components-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-host';
  user = '';
  @HostListener('document:user-selected', ['$event.detail'])
  changeColor(user: string): void {
    console.log(user);
    this.user = user;
  }
}

<div class="content">
  <div class="sidebar">
    <div class="sidebar-header">
      <img src="assets/angular-icon.svg" width="100px" alt="Angular Icon" />
      <h1>Angular Host</h1>
    </div>
    <ul class="remote-menu">
      <li><a routerLink="/">Home</a></li>

      <li><a routerLink="angular-module">Angular Module</a>
        <ul>
          <li><a routerLink="/angular-module/material">Material</a></li>
        </ul>
      </li>

      <li><a routerLink="react-module">React Module</a>
        <ul>
          <li><a href="/react-module/mui">MUI</a></li>
        </ul>
      </li>

      <li><a href="/multiple">Multiple Apps</a></li>
      <li><a href="/shadow-angular-module">Shadow DOM Angular</a></li>
      <li><a href="/shadow-react-module">Shadow DOM React</a></li>
      <li>
        <a href="/iframe">iFrame</a>
      </li>
    </ul>
    <p class="user" *ngIf="user">Hello {{this.user}}!</p>
  </div>
  <div class="federated-module">
    <router-outlet></router-outlet>
  </div>
</div>

// apps/react-module/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.css';
import { Route, Link, Routes } from 'react-router-dom';
import Home from './home/home';
import Mui from './mui/mui';
import MultipleEntry from './multiple-entry/multiple-entry';

export function App() {
  return (
    <>
      <div className="module-content-header">
        <img
          className={styles['react_logo']}
          src="assets/react-icon.svg"
          width="80px"
          alt="React Icon"
        />
        <h2>React Remote Component</h2>
          <nav>
            <ul className="page-menu">
              <li>
                <Link to="/react-module">
                  Home
                </Link>
              </li>
              <li>
                <Link to="/react-module/mui">
                  MUI
                </Link>
              </li>
              <li>
                <a href="/">
                  Host-Home
                </a>
              </li>
            </ul>
          </nav>
      </div>
      <div className="module-content">
        <Routes>
          <Route path="/react-module" element={<Home />} />
          <Route path="/react-module/mui" element={<Mui />} />
          <Route path="/multiple" element={<MultipleEntry />} />
        </Routes>
      </div>
    </>
  );
}

export default App;
