// apps/angular-host/src/app/shadow-wrapper.component.ts
import {
  AfterContentInit,
  Component,
  ElementRef,
  Input,
  ViewChild,
  ViewEncapsulation,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { registry, Registry } from './registry';

@Component({
  selector: 'module-federation-web-components-shadow-wrapper',
  template: '<div #vc></div>',
  encapsulation: ViewEncapsulation.ShadowDom
})
export class ShadowWrapperComponent implements AfterContentInit {
  @ViewChild('vc', { read: ElementRef, static: true })
  vc!: ElementRef;

  @Input()
  elementName!: string;

  @Input()
  importName!: keyof Registry;

  constructor(private route: ActivatedRoute) {}

  ngAfterContentInit(): void {
    const elementName = this.elementName ?? this.route.snapshot.data['elementName'];
    const importName: keyof Registry = this.importName ?? this.route.snapshot.data['importName'];

    const element = document.createElement(elementName);
    this.vc.nativeElement.appendChild(element);

    const importFn = registry[importName];
    importFn()
      .then()
      .catch((err: any) => console.error(`error loading ${elementName}:`, err));
  }
}

// apps/react-host/src/app/wrapper/shadow-wrapper.tsx
import React from 'react';
import { Registry, registry } from './registry';

/* eslint-disable-next-line */
export interface WrapperProps {
  elementName: string;
  importName: keyof Registry;
}

export class ShadowWrapper extends React.Component<WrapperProps> {
  importName: keyof Registry;
  element: HTMLElement;

  constructor(props: WrapperProps) {
    super(props);
    const { elementName, importName } = props;
    this.element = document.createElement(elementName);
    this.importName = importName;
  }

  override componentDidMount() {
    const importFn = registry[this.importName];
    importFn()
      .then()
      .catch((err: any) =>
        console.error(`error loading ${this.importName}:`, err)
      );
  }

  attachShadow = (host: HTMLDivElement) => {
    if (host) {
      const shadow = host.attachShadow({ mode: 'open' });
      shadow.appendChild(this.element);
    }
  };
  override render() {
    return <div ref={this.attachShadow}></div>;
  }
}

export default ShadowWrapper;
