// apps/angular-host/src/app/wrapper.component.ts
import {
  AfterContentInit,
  Component,
  ElementRef,
  Input,
  OnInit,
  ViewChild,
  ViewContainerRef,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { registry, Registry } from './registry';

@Component({
  selector: 'module-federation-web-components-wrapper',
  template: '<div #vc></div>',
})
export class WrapperComponent implements AfterContentInit {
  @ViewChild('vc', { read: ElementRef, static: true })
  vc!: ElementRef;

  @Input()
  elementName!: string;

  @Input()
  importName!: keyof Registry;

  constructor(private route: ActivatedRoute) {}

  ngAfterContentInit(): void {
    const elementName = this.elementName ?? this.route.snapshot.data['elementName'];
    const importName: keyof Registry = this.importName ?? this.route.snapshot.data['importName'];

    const element = document.createElement(elementName);
    this.vc.nativeElement.appendChild(element);

    const importFn = registry[importName];
    importFn()
      .then()
      .catch((err: any) => console.error(`error loading ${elementName}:`, err));
  }
}

// apps/react-host/src/app/wrapper/wrapper.tsx
import React from 'react';
import { Registry, registry } from './registry';
import styles from './wrapper.module.css';

/* eslint-disable-next-line */
export interface WrapperProps {
  elementName: string;
  importName: keyof Registry;
}

export function Wrapper(props: WrapperProps) {
  const { elementName, importName } = props;
  const element = React.createElement(elementName);

  const importFn = registry[importName];
    importFn()
      .then()
      .catch((err: any) => console.error(`error loading ${elementName}:`, err));

  return (
    <div className={styles['wrapper']}>
    { element }
    </div>
  );
}

export default Wrapper;
