// apps/react-host/src/app/multiple-apps/multiple-apps.tsx
import Wrapper from '../wrapper/wrapper';
import styles from './multiple-apps.module.css';

/* eslint-disable-next-line */
export interface MultipleAppsProps {}

export function MultipleApps(props: MultipleAppsProps) {
  return (
    <div className={styles['container']}>
      <Wrapper importName="react-module" elementName="react-module-root" />
      <Wrapper importName="angular-module" elementName="angular-module-root" />
    </div>
  );
}

export default MultipleApps;

// apps/angular-host/src/app/multiple-apps/multiple-apps.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'module-federation-web-components-multiple-apps',
  templateUrl: './multiple-apps.component.html',
  styleUrls: ['./multiple-apps.component.css'],
})
export class MultipleAppsComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<module-federation-web-components-wrapper importName="angular-module" elementName="angular-module-root"></module-federation-web-components-wrapper>
<module-federation-web-components-wrapper importName="react-module" elementName="react-module-root"></module-federation-web-components-wrapper>
