// apps/react-host/src/app/home/home.tsx
import styles from './home.module.css';

/* eslint-disable-next-line */
export interface HomeProps {}

export function Home(props: HomeProps) {
  return (
    <div className={styles['container']}>
      <div className="module-content-header">
        <img
          className="react-icon"
          src="assets/react-icon.svg"
          width="90px"
          alt="React Icon"
        />{' '}
        <h1>React Component</h1>
      </div>
      <div className="module-content">
        <h1>Welcome to micro frontends and the multiverse of frameworks!</h1>
        <p>
          This page is a simple React component, but we are about to see
          something special, Module Federation + Web Components!{' '}
        </p>

        <div className="home-icons">
          <img
            src="assets/wc-mod-fed.png"
            width="50%"
            alt="Module Federation logo"
          />
        </div>
      </div>
    </div>
  );
}

export default Home;

// apps/angular-host/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'module-federation-web-components-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class="module-content-header">
  <img src="assets/angular-icon.svg" width="100px" alt="Angular Icon" />
  <h1>Angular Component</h1>
</div>
<div class="module-content">
  <h1>Welcome to micro frontends and the multiverse of frameworks!</h1>
  <p>
    This page is a simple Angular component, but we are about to see something special, Module Federation + Web
    Components! </p>
  <div class="home-icons">
    <img src="assets/modfed.jpg" width="50%" alt="Module Federation logo" />
    <h1 class="plus"> + </h1>
    <img src="assets/wc-logo.svg" width="50%" alt="web components logo" />
  </div>
</div>
